export const ROUTES = {
  root: '/',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  users: '/users',
  audit: '/audit',
  tournaments: '/tournaments',
  tournamentsNew: '/tournaments/new',
  tournamentDetail: '/tournaments/:id',
  tournamentEdit: '/tournaments/:id/edit',
  tournamentParticipants: '/tournaments/:id/participants',
  tournamentRounds: '/tournaments/:id/rounds',
  roundDetail: '/rounds/:id',
  roundMatches: '/rounds/:id/matches',
  voteHome: '/vote',
  voteTournaments: '/vote/tournaments',
  voteTournament: '/vote/tournaments/:id',
  voteRound: '/vote/rounds/:id',
  voteMatch: '/vote/matches/:id',
} as const
